### ISSUE TITLE
Issues with some of the new definitions

### ISSUE THREAD

**Issue by kevinstrick** [SavingThrows/AdwareDefinitionFiles#4]
I added all the new definitions to my script "NEFARIOUS_FILE_SOURCES ",
and the following definitions don't seem to work right now---

BestYouTubeDownloader.adf
Bundlore.adf
ZipCloud.adf

**Comment by sheagcraig** [comment]
@kevinstrick Wow! You were on the ball yesterday! I haven't even set them up for our org.

So, some of these are definitely a work in progress, as they all come from a contribution, and they have commented out sections which I'm working on (hopefully today).

I'll take a look at the ones you mentioned also. Thanks!

**Comment by kevinstrick** [comment]
@sheagcraig I was just on a tear to update the adware stuff, it was all timing :)

**Comment by sheagcraig** [comment]
Everything should be ready. I'm doing some last tests, and trying to incorporate some process killing into a few, but look for an update to SavingThrow and updated adf's later this morning.
