### ISSUE TITLE
GoPhoto defs flag every Firefox prefs.js

### ISSUE THREAD

**Issue by RobertHammen** [SavingThrows/AdwareDefinitionFiles#5]
Tried this on a few machines, some which I know don't have adware on them. Flagged every time. Looked at the prefs.js file and found nothing out of the ordinary. Looked at the definition and it seems incomplete.

**Comment by sheagcraig** [comment]
Yeah-these are unintentional artifacts of converting these definitions from elsewhere. I'm not super-well versed in Firefox's structure, but prefs.js is probably exactly what it sounds like-a javascript file that Firefox stores its prefs in. The original source is probably really aggressive about removing it IF it finds the other files. Since SavingThrow is just looking for matches, that won't work. I'll take a look.

**Comment by RobertHammen** [comment]
Yeah, I think the definition file needs to be looking into the content of the prefs.js file, not it existence itself, which is what it seemed like it was doing to me. And you're right, prefs.js is where Firefox stores its preferences.

**Comment by sheagcraig** [comment]
@RobertHammen The prefs for Chrome and Firefox have been commented out on all of the new recipes now.

**Comment by charliwest** [comment]
Is this similar, what I am seeing is this sort of report?
Name: Vidx/MacVX
File 1: /Users/user/Library/Application Support/Google/Chrome/Default/Preferences
Name: Awesome Screenshot
File 1: /Users/user/Library/Application Support/Google/Chrome/Default/Preferences
Name: OperatorMac
File 1: /Users/user/Library/Application Support/Google/Chrome/Default/Preferences
Looks like its saying the Preferences file itself is the problem, am I misunderstanding it?

**Comment by sheagcraig** [comment]
Those files should all be present in the ADF's, but commented out. It's
possible that the above-referenced Adware's can add stuff to the
preferences, but we're not comfortable saying we should delete that entire
file yet.

Are you using the definitions "raw" right off of SavingThrows, or have you
forked it (recommended!)? If so, you may need to do a `git pull origin
master` or similar to get the changes. I'll check to make sure they are
commented out though just to be safe!

**Comment by sheagcraig** [comment]
My bad-there were some closing tag issues that prevented a bunch of the adf's from being valid xml. They should now be clean.

**Comment by charliwest** [comment]
Cheers, I found the misbehaving one and removed it actually as I read in it it said for testing and now to use it, will add it back now.

Thanks
