### ISSUE TITLE
Public or Private repo?

### ISSUE THREAD

**Issue by YesThatAllen** [SavingThrows/AdwareDefinitionFiles#8]
The Watchman Monitoring team has decided to adopt this ADF format, and will be submitting a PR to submit ours for the community.

Before we do that, I'd like to start the discussion on the pros & cons of:
### Maintaining ADFs out in the open for:
- full disclosure
- better visibility in the community 
- free github hosting

vs 
### Gathering ADFs in a private repo that “good guys” can see
- Protection against malware makers learning to adapt to the ADF ways?
- needing someone to sponsor the repo & manage access

I'd be glad to share responsibility for management, but I just don't know the best answer here. Good guys could certainly request access in 

https://macadmins.slack.com/archives/savingthrow/

**Comment by YesThatAllen** [comment]
This was the balance I took when we were faced with the same question...

Public repo stating what was included, private list of exactly how.
https://github.com/watchmanmonitoring/Malware_Tests

**Comment by sheagcraig** [comment]
FWIW, my perception is that the guys writing mac crapware are not going to bother seeing how we block stuff: Their stuff is _very_ simplistic.

That being said, what I don't understand is that for those I've dug through, the binaries are signed by Apple Developer ID's. Why have these ID's not been blacklisted by XProtect? I'm sure we could do the same with Google Santa, but it would be nice of Apple were to do so. They're quick to take down infringing apps on the app store, but it seems like using misdirection and outright lying to get someone to install your "app" which then just takes over your browser and generates adclick revenue is a serious enough offense to get your Developer ID revoked. Not that they couldn't just get a new one, but at least it costs some money.

**Comment by sheagcraig** [comment]
In terms of the SavingThrows organization, this is a public repo, with open sourced, community generated content, and will remain that way. I think the difference between this solution and others is its transparency; it is up to individual admins to use this information to verify that it does what they want, that it is correct, and up to date. Adding a layer of protection would undermine the nature of this relationship.
